

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_USER_DATA_REQUEST = 'FETCH_USER_DATA_REQUEST';

export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';

export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';

export const POST_USER_DATA_REQUEST = 'POST_USER_DATA_REQUEST';

export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS';

export const POST_USER_DATA_FAILURE = 'POST_USER_DATA_FAILURE';

export const DELETE_CATEGORY_REQ = 'DELETE_USER_DATA_CATEGORY';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const POST_BILL_REQ = 'POST_BILL_REQ';

export const POST_BILL_SUCCESS = 'POST_BILL_SUCCESS';

export const POST_BILL_FAIL = 'POST_BILL_FAIL';

export const DELETE_BILL_REQ = 'DELETE_USER_BILL';

export const DELETE_BILL_SUCCESS = 'DELETE_BILL_SUCCESS';

export const DELETE_BILL_FAIL = 'DELETE_BILL_FAIL';

export const LOG_USEROUT_REQ = 'LOG_USEROUT_REQ';

export const LOG_USEROUT_FAIL = 'LOG_USEROUT_FAIL';

export const LOG_USEROUT_SUCCESS = 'LOG_USEROUT_SUCCESS';

export const USER_REGIS_REQ = 'USER_REGIS_REQ';

export const USER_REGIS_SUCCESS = 'USER_REGIS_SUCCESS';

export const USER_REGIS_FAIL = 'USER_REGIS_FAIL';
