

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_USER_DATA_REQUEST = 'FETCH_USER_DATA_REQUEST';

export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';

export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';

export const POST_USER_DATA_REQUEST = 'POST_USER_DATA_REQUEST';

export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS';

export const POST_USER_DATA_FAILURE = 'POST_USER_DATA_FAILURE';


